### ISSUE TITLE
Errors seen in log after upgrade to core-2021.8.6

### ISSUE THREAD

**Issue by HACS-bank** [markgdev/home-assistant_OctopusAgile#85]
**Describe the bug**
compatibility with core-2021.8.6 may need work

**To Reproduce**
upgrade to core-2021.8.6

**Expected behavior**
no errors

**Log**
2021-08-13 18:00:00 ERROR (SyncWorker_7) [custom_components.octopusagile.sensor] Error updating sensor.octopus_agile_previous_rate, check that octopusagile.all_rates populated
2021-08-13 18:00:00 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.octopus_agile_next_rate fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/octopusagile/sensor.py", line 228, in update
    next_rate = round(next_rate, 2)
TypeError: type NoneType doesn't define __round__ method
2021-08-13 18:00:00 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.octopus_agile_current_rate fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/octopusagile/sensor.py", line 160, in update
    current_rate = round(current_rate, 2)
TypeError: type NoneType doesn't define __round__ method

**System (please complete the following information):**
## System Health

version | core-2021.8.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.52-v7+
arch | armv7l
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4993
Installed Version | 1.13.2
Stage | running
Available Repositories | 843
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

**Additional context**

**Comment by benjsec** [comment]
I have started noticing the same after updating to 2021.9.2 yesterday. I also see this in the logs as well as the previous snippet
```Logger: custom_components.octopusagile
Source: custom_components/octopusagile/__init__.py:413
Integration: octopusagile (documentation, issues)
First occurred: 13:30:10 (3 occurrences)
Last logged: 17:30:24
Expecting value: line 1 column 1 (char 0)``` and note that the `octopusagile.all_rates` state doesn't look to have updated properly since I upgraded.
I was previously using OctopusAgile `v0.1.1` and have since tried updating to `v0.1.2-beta.3` which does not seem to have had any noticeable effect on this issue.
