### ISSUE TITLE
Extra Data Error during setup of component octopusagile

### ISSUE THREAD

**Issue by AndrewGWalsh** [markgdev/home-assistant_OctopusAgile#94]
I get this error on startup.  I have only recently got octopus agile.  The curl command son the octopus agile api page work.

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/octopusagile/__init__.py:69 
Integration: octopusagile (documentation, issues) 
First occurred: 10:49:23 (1 occurrences) 
Last logged: 10:49:23

Error during setup of component octopusagile
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/octopusagile/__init__.py", line 69, in setup
    data = json.load(f)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3589 (char 3588)

**Comment by BettySwallocks** [comment]
Same error started for me just after 2022.11 update at start of November 2022.
